In [ ]:
# Create a 3x3 matrixs with random integer from 1 to 10.

import numpy as np

a = np.random.randint( 1,10, size=(3,3))
b = np.random.randint(1,10, size=(3,3))

print("Matrix A: \n", a)
print("Matrix B: \n", b)


Matrix A: 
 [[2 3 7]
 [5 6 8]
 [2 9 7]]
Matrix B: 
 [[9 5 8]
 [7 5 2]
 [9 6 1]]


In [ ]:
# Addition, substraction and multiplication of a matrix.

add = a + b
sub = a - b 
multi = a * b

print("Addition of A and B : \n", add)
print("Substraction of A and B : \n", sub)
print("Multiplication of A and B : \n", multi)

Addition of A and B : 
 [[11  8 15]
 [12 11 10]
 [11 15  8]]
Substraction of A and B : 
 [[-7 -2 -1]
 [-2  1  6]
 [-7  3  6]]
Multiplication of A and B : 
 [[18 15 56]
 [35 30 16]
 [18 54  7]]


In [ ]:
# Transpose and Inverse of Matrix.

a_T = a.T
print("Transpose of a \n", a_T)


if np.linalg.det(a) != 0:
    A_inv = np.linalg.inv(a)
    print("Inverse of a \n", A_inv)
else:
    print("Matrix is not inversible")

Transpose of a 
 [[2 5 2]
 [3 6 9]
 [7 8 7]]
Inverse of a 
 [[-2.63157895e-01  3.68421053e-01 -1.57894737e-01]
 [-1.66666667e-01  8.41078049e-18  1.66666667e-01]
 [ 2.89473684e-01 -1.05263158e-01 -2.63157895e-02]]


In [ ]:
# Compare Speed

import time

def python_add(a,b):
    return [[a[i][j] + b[i][j] for j in range(len(a[0]))] for i in range(len(a))]

a_list = a.tolist()
b_list = b.tolist()

start = time.time()
python_result = python_add(a_list , b_list)
end = time.time()
print("Python addition took:", end - start,"Seconds")

start = time.time()
numpy_result = a + b
end = time.time()
print("Numpy addition took:", end - start,"Seconds")



Python addition took: 4.1961669921875e-05 Seconds
Numpy addition took: 0.00011086463928222656 Seconds
